# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0


include:
  - ../../../third_parties/qdrant/deployment/docker_compose/compose.yaml
  - ../../../third_parties/vllm/deployment/docker_compose/compose.yaml

services:

  dataprep-qdrant:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-qdrant-server
    depends_on:
      qdrant-vector-db:
        condition: service_healthy
      tei-embedding-serving:
        condition: service_healthy
    ports:
      - "${DATAPREP_PORT:-5000}:5000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_QDRANT"
      QDRANT_HOST: ${QDRANT_HOST}
      QDRANT_PORT: ${QDRANT_PORT}
      COLLECTION_NAME: ${COLLECTION_NAME}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      HF_TOKEN: ${HF_TOKEN}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/v1/health_check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  dataprep-qdrant-offline:
    extends: dataprep-qdrant
    depends_on:
      qdrant-vector-db:
        condition: service_healthy
      tei-embedding-serving:
        condition: service_healthy
    environment:
      HF_HUB_OFFLINE: 1
      # Use non-existing proxy to mimic air gapped environment
      no_proxy: localhost,127.0.0.1,${offline_no_proxy}
      http_proxy: http://localhost:7777
      https_proxy: http://localhost:7777
    volumes:
      - "${DATA_PATH:-./data}:/data"

networks:
  default:
    driver: bridge
  opensearch-net:
